services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: ontology-mapper-api
    environment:
      - BASEURL=${DOMAIN}
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: ontology-mapper-client
    environment:
      - BASEURL=${DOMAIN}
    ports:
      - "8602:80"
