# Build Flask API
FROM python:3.9
WORKDIR /app

COPY flask-api/* ./
RUN mkdir output
RUN mkdir input
## mainly for easy testing; should be able to get rid of when can stop navigating directly to results
RUN pip install -r ./requirements-flask.txt
ENV FLASK_ENV production

WORKDIR /app

EXPOSE 8601
CMD ["gunicorn", "-b", ":8601", "-w","2", "flask-api:app"]
